# Generated by Django 3.0.5 on 2020-04-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200420_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
